#!/usr/bin/env python
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from market_maker import market_maker
if __name__ == "__main__":
    market_maker.run()
